services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5432:5432" # Expose PostgreSQL port

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - app_network
    ports:
      - "6379:6379" # Expose PostgreSQL port

volumes:
  db_data:
  redis_data:


networks:
  app_network:
    driver: bridge
